version: "2.3"
services:

  pepperhri:
    image: pepper-hri
    container_name: pepperhri
    tty: true
    ipc: host
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/robot/.Xauthority
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME}/playground:/home/robot/playground
      - $HOME/src/Pepper/pepper_tools:/home/robot/src/pepper_tools
    working_dir: /home/robot/
    entrypoint:
    - bash
    - -ci 
    - "cd /home/robot/ && ./init.bash"


